#!/bin/bash
# Name: myscript_q2
# Description: Automate MLFQ runs for chapter 8 question 2 to reproduce chapter's examples.

echo "===================================================================================="
echo                  "Running chapter : question 2 Textbook Examples"
echo "===================================================================================="

#creating an array of workload matching example 8.1, 8.2, 8.3 to be processed by the simultaneously.
workloads=(
	"0,200,0" 	# Example 1 Single long running job 
	"0,200,0:100,20,0" # Example 2 : Along came a short running job 
	"0,200,0:50,20,1" # Example 3: Mixed I/0-intensive and CPU entensive Worloads
)

for w in "${workloads[@]}"; do 
	python3 ./mlfq.py -n3 -l "$w" -c 
	echo "----------------------------------------------------------------------------------------"
done

echo "All chapter8 Question 2 simulation completed!"
